### ISSUE TITLE
Documentation regarding use of docker

### ISSUE THREAD

**Issue by thinkbig1979** [jsreport/jsreport#1139]
Hi all,

just wanted to add some info for the documentation regarding docker usage, as you docs do not really cover this in enough detail:

Please note that if you plan to persist data to your local file system, your file permissions for the mounted folders need to be  accurate.
- Create a user called `jsonreport` with UID 2500, and a group called `jsonreport` with GID 2500 on your machine
- Add the user to the group.
- Create the `data`  mount point that you want to use 
- Put the config file where you see fit.
- Make sure you set ownership of the data folder and it's contents to the jsreport:jsrepor, and do the same for the config file.
- Mount the data file and the config file as shown in the compose file below.
- Note that the config file needs to contain a complete config with accurate syntax, or you will have issues with your deployment. The only reason to have the config file mounted is if you want to change the default config. In the example below I've enabled the `trustUserCode` property. You can also use sandboxing to enable specific JS modules in your reports. 

Following these instructions should give you a working system. 

### Docker Compose example:

```yaml
version: "3.4"
services:
  jsreport:
    image: jsreport/jsreport
    container_name: jsreport
    #ports:
    #  - 5488:5488
    volumes:
      - ./data:/app/data
      - ./jsreport.config.json:/app/jsreport.config.json
    restart: unless-stopped
    environment:
      - extensions_authentication_admin_username=${USER}
      - extensions_authentication_admin_password=${PASSWORD}
      - extensions_authentication_cookieSession_secret=${SECRET}
``` 
Don't forget to create a .env file with the appropriate variables. 
e.g.

```env
SECRET=GenerateYourOwn32CharacterSecret
USER=YourUsername
PASSWORD=YourPassword
```

### Config file example:
(Note that the ports section is commented out. This is because I use a reverse proxy, and don't want these ports exposed on my host machine, change to suit your own use case):

```json
{
    "httpPort": 5488,
    "trustUserCode": true,
    "store": {
        "provider": "fs"
    },
    "logger": {
        "console": {
            "transport": "console",
            "level": "debug"
        },
        "file": {
            "transport": "file",
            "level": "info",
            "filename": "logs/reporter.log"
        },
        "error": {
            "transport": "file",
            "level": "error",
            "filename": "logs/error.log"
        }
    },
    "trustUserCode": false,
    "reportTimeout": 60000,
    "workers": {
        "numberOfWorkers": 2
    },
    "extensions": {},
}
```
