### ISSUE TITLE
Insert page break

### ISSUE THREAD

**Issue by johntom** [jsreport/jsreport#212]
Hi,
In my initial test as I extended my dataset in your basic book/author sample data the chart split on the bottom and top of another page. Can on force a page break so that the chart always starts on a new page?
Header
h2 Book sales chart /h2
Chart
Thanks,
John

**Comment by pofider** [comment]
The standard solution would be to use css -  `page-break-inside:avoid`

However there is bug in phantomjs which doesn't apply this style correctly
https://github.com/ariya/phantomjs/issues/10638

Fortunately there is mentioned existing workaround:
```css
.unbreakable
{
    /* page-break-inside: avoid !important; <-- doesn't work*/
    display:inline-block;
}
.unbreakable:after
 {
    display:block;
    height:0px;
    visibility: hidden;
}
```

You can see this in action in playground
https://playground.jsreport.net/#playground/lkHFBn0xB/557
