### ISSUE TITLE
Auto pagination for phantom pdf 

### ISSUE THREAD

**Issue by dineshu07** [jsreport/jsreport#241]
Hi 

I'm playing with jsreport. one thing i'm not albe to do that is auto pagination for phantom pdf. i found this 
<style>
 .page-break {
        display: block;
        page-break-before: always;
    }
</style>
<div class="page-break"></div>

I'm writing javascript to generate dynamic tables with charts. how to get it automatically page breaks without hard coding page breaks in template. if I'm not using page breaks pdf is generated like this 

![screenshot from 2016-09-20 12 54 40](https://cloud.githubusercontent.com/assets/13025236/18661051/77530088-7f31-11e6-8d71-b0a5f07b0ac3.png)

![screenshot from 2016-09-20 12 54 48](https://cloud.githubusercontent.com/assets/13025236/18661055/7ef9f292-7f31-11e6-8097-22157c3bb77a.png)

**Comment by pofider** [comment]
Hi, 

you need to add style `page-break-inside: avoid;` to the chart placeholder.
This works nicely in `electron-pdf` recipe and also if you enable [phantomjs2 in phantom-pdf](http://jsreport.net/learn/phantom-pdf)

Unfortunately it doesn't work by default (with phantomjs 1.9), so you need to use a little workaround mentioned [here in this issue](https://github.com/ariya/phantomjs/issues/10638#issuecomment-20186253)

```css
<style>
    .unbreakable
    {
        /* page-break-inside: avoid !important; <-- doesn't work*/
        display:inline-block;
    }
    .unbreakable:after
     {
        display:block;
        height:0px;
        visibility: hidden;
    }
</style>
```
