### ISSUE TITLE
Docker For Windows Volume Mount not working

### ISSUE THREAD

**Issue by matthewjcooper** [jsreport/jsreport#266]
When i us the following in my docker-compose file with docker for windows:

`  health-here-report:
    build:
      context: ./JsReport
    expose: 
      - "5488"
    ports:
      - "5488:5488"`

Everything works fine

When I modify this service to use volume mapping like so:

 ```
health-here-report:
    build:
      context: ./JsReport
    expose: 
      - "5488"
    ports:
      - "5488:5488"
    volumes: 
      - ./JsReport/jsreport:/jsreport
```

I get the errors below. I do not have this error when running with docker for mac or docker native on Linux.

![image](https://cloud.githubusercontent.com/assets/1433729/23096254/110fa9ce-f5de-11e6-88e5-02157b0b4cdc.png)
