### ISSUE TITLE
jsreport render bigger on server than local server

### ISSUE THREAD

**Issue by f1lander** [jsreport/jsreport#269]
Hi, I'm working with jsreports to generate some reports to pdf, the issue that I have is rendering the report on the server, is generated without problems but it's seems bigger the font of the report and the size of my table.

![image](https://cloud.githubusercontent.com/assets/5679878/23379072/19a9ba4c-fcfb-11e6-8329-ca925952add8.png)

But local seems good.

![image](https://cloud.githubusercontent.com/assets/5679878/23379590/20284544-fcfd-11e6-9ef4-e4258c7f289d.png)

I'm using:

"jsreport": "1.4.0",

Server:
Ubuntu on digital ocean

Thanks,

**Comment by pofider** [comment]
This known issue and we need to better document it.

The reason is that phantomjs renders different sizes on different platforms. The solution which can work for you is to add css transform scale to zoom out or in on particular platform.

```css
body { 
  transform-origin: 0 0; 
  -webkit-transform-origin: 0 0; 
  transform: scale(0.654545); 
  -webkit-transform: scale(0.654545); 
}
```

https://github.com/pofider/phantom-html-to-pdf/pull/16
