### ISSUE TITLE
chrome-pdf timeout doesn't work?

### ISSUE THREAD

**Issue by lichutin-st** [jsreport/jsreport#848]
Hello, I've just tried v3 version of jsreport.

I'm generating pdfs from large html documents and it usually takes 5-10 minutes.
Everything works fine in v2, but v3 fails with exception
```
waiting for Page.printToPDF failed: timeout 30000ms exceeded

TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded\n    at Object.waitWithTimeout (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:224:26)\n    at Page.createPDFStream (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2045:49)\n    at Page.pdf (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2057:37)\n    at /app/node_modules/@jsreport/jsreport-chrome-pdf/lib/conversion.js:336:27\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /app/node_modules/@jsreport/jsreport-chrome-pdf/lib/conversion.js:377:22
```

I tried images from docker hub (3.11 & 3.11-full).
Neither env variables nor config file modification helped.

Example of env variables (cut from compose file, some of them may make no sense for jsreport v3):
```
  jsreport:
    image: jsreport/jsreport:3.1.1-full
    container_name: "jsreport"
    ports:
      - "35488:5488"
    environment:
      chrome_strategy: "chrome-pool"
      chrome_numberOfWorkers: 1 # equals to number of available proc cors
      chrome_launchOptions_args": "--no-sandbox"
      templatingEngines_strategy: "http-server"
      #enableRequestReportTimeout: "true"
      reportTimeout: "10000000"
      chrome_timeout: "10000000"
      extensions_chromePdf_timeout: "10000000"
```

Is that possible that chrome timeout is being ignored? Or I'm wrong with the configuration?
